(() => {
  'use strict';
  if(!window.NougatWebModules)return;
  const previous=window.NougatWebModules.activate.bind(window.NougatWebModules);
  const root=()=>document.getElementById('moduleView');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const button=(label,id,active=false,extra='')=>`<button type="button" class="sheet-button${active?' active-tool':''}" id="${id}" ${extra}>${esc(label)}</button>`;
  const bind=(id,fn)=>{const el=document.getElementById(id);if(el)el.addEventListener('click',fn);};
  const shell=html=>{const r=root();if(!r)return null;r.innerHTML=`<div class="module-workspace">${html}</div>`;return r.querySelector('.module-workspace');};
  const BUILTIN_LOGOS=[
    [/(PBS\s*KIDS|PBSKIDS)/i,'pbs_kids.bmp'],[/ION\s*PLUS/i,'ion_plus.bmp'],[/\bNBC\b/i,'nbc.bmp'],[/\bPBS\b/i,'pbs.bmp'],[/TELEMUNDO/i,'telemundo.bmp'],[/\bABC\b/i,'abc.bmp'],[/\bCBS\b/i,'cbs.bmp'],[/\bFOX\b/i,'fox.bmp'],[/\bCW\b/i,'cw.bmp'],[/ME\s*TV|METV/i,'metv.bmp'],[/\bION\b/i,'ion.bmp'],[/\bCREATE\b/i,'create.bmp'],[/\bBOUNCE\b/i,'bounce.bmp'],[/\bBUSTED\b/i,'busted.bmp'],[/SHOP\s*LC|SHOPLC/i,'shoplc.bmp']
  ];
  let hostRef=null;
  let selectedId='';
  let channels=[];
  let programs=[];
  let tuner=null;
  let keyboardBound=false;

  function base(){return hostRef?.baseUrl?hostRef.baseUrl():'';}
  async function call(action,extra={}){const params=new URLSearchParams({action,...extra});const response=await fetch(`${base()}/nougat/v1/live-tv?${params}`,{cache:'no-store'});let data={};try{data=await response.json();}catch(_){data={};}if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data;}
  function remember(){try{localStorage.setItem('nougat-web-live-tv-cache',JSON.stringify({channels,programs,tuner,selectedId,when:Date.now()}));}catch(_){}}
  function restore(){try{const x=JSON.parse(localStorage.getItem('nougat-web-live-tv-cache')||'{}')||{};channels=Array.isArray(x.channels)?x.channels:[];programs=Array.isArray(x.programs)?x.programs:[];tuner=x.tuner||null;selectedId=String(x.selectedId||'');}catch(_){}}
  function channelId(c){return String(c.id||c.channel_id||c.channel||c.program_number||'');}
  function programChannelId(p){return String(p?.channel_id||p?.channelId||p?.channel||p?.program_number||'');}
  function channelName(c){return String(c.name||c.service||`Channel ${channelId(c)}`);}
  function builtinChannelLogo(c){const haystack=[c?.name,c?.service,c?.network,c?.affiliate,c?.callsign,c?.call_sign].filter(Boolean).join(' ');const hit=BUILTIN_LOGOS.find(([pattern])=>pattern.test(haystack));return hit?`./assets/channel_logos/builtin/${hit[1]}`:'';}
  function channelLogo(c){
    const value=String(c.logo||c.logo_url||c.logoUrl||c.image||c.image_url||c.icon||'').trim();
    if(value){if(/^https?:\/\//i.test(value)||value.startsWith('data:')||value.startsWith('blob:'))return value;if(value.startsWith('/'))return `${base()}${value}`;try{return new URL(value,`${base()}/`).href;}catch(_){}}
    return builtinChannelLogo(c);
  }
  function channelIdentity(c){const logo=channelLogo(c);const number=esc(c.virtual_channel||c.channel||c.physical_channel||'');const image=logo?`<img data-live-channel-logo src="${esc(logo)}" alt="" loading="lazy">`:'';return `<span class="live-tv-channel-identity">${image}<span><b>${number}</b> ${esc(channelName(c))}</span></span>`;}
  function epochSeconds(value){if(value===null||value===undefined||value==='')return 0;const n=Number(value);if(Number.isFinite(n)&&n>0)return n>100000000000?Math.round(n/1000):n;const parsed=Date.parse(String(value));return Number.isFinite(parsed)?parsed/1000:0;}
  function programStart(p){return epochSeconds(p?.start_unix??p?.start??p?.start_time??p?.startTime??p?.starts_at);}
  function programEnd(p){const explicit=epochSeconds(p?.end_unix??p?.end??p?.end_time??p?.endTime??p?.ends_at);if(explicit)return explicit;const start=programStart(p);if(!start)return 0;const ms=Number(p?.duration_ms||0);if(Number.isFinite(ms)&&ms>0)return start+(ms/1000);const seconds=Number(p?.duration_seconds??p?.duration??0);if(Number.isFinite(seconds)&&seconds>0)return start+(seconds>604800?seconds/1000:seconds);const next=programs.filter(x=>programChannelId(x)===programChannelId(p)&&programStart(x)>start).sort((a,b)=>programStart(a)-programStart(b))[0];return next?programStart(next):0;}
  function nowProgram(id){const now=Date.now()/1000;return programs.filter(p=>programChannelId(p)===id).sort((a,b)=>programStart(a)-programStart(b)).find(p=>{const start=programStart(p),end=programEnd(p);return start>0&&start<=now&&end>now;});}
  function nextProgram(id){const now=Date.now()/1000;return programs.filter(p=>programChannelId(p)===id&&programStart(p)>now).sort((a,b)=>programStart(a)-programStart(b))[0];}
  function time(unix){if(!Number(unix))return '';return new Date(Number(unix)*1000).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});}
  function timeRange(p){if(!p)return '';const start=programStart(p),end=programEnd(p);if(!start)return '';return end?`${time(start)} - ${time(end)}`:time(start);}
  function programTitle(p){return String(p?.title||p?.name||p?.program||'Untitled program');}
  function programProgress(p){const start=programStart(p),end=programEnd(p),now=Date.now()/1000;if(!start||!end||end<=start)return 0;return Math.max(0,Math.min(100,((now-start)/(end-start))*100));}
  function guideRows(){return channels.length?channels.map(c=>{const id=channelId(c),now=nowProgram(id),next=nextProgram(id);return `<button type="button" class="module-result-row${selectedId===id?' active-tool':''}" data-live-guide-id="${esc(id)}">${channelIdentity(c)}<span>${now?`${esc(timeRange(now))} ${esc(programTitle(now))}`:'No current guide data'}</span><span>${next?`NEXT ${esc(time(programStart(next)))} ${esc(programTitle(next))}`:''}</span></button>`;}).join(''):'<div class="module-empty">No saved channels. Scan the tuner from this page, or use System for tuner detection and refresh.</div>';}
  function tunerTable(){if(!tuner)return '<div class="module-output">No tuner status has been returned by the Nougat host. Tuner detection and refresh are in System.</div>';return `<table class="diagnostic-table"><tbody><tr><th>Device</th><td>${esc(tuner.name||tuner.id||'Tuner')}</td></tr><tr><th>Backend</th><td>${esc(tuner.backend||'Unknown')}</td></tr><tr><th>Status</th><td>${esc(tuner.status||'Unknown')}</td></tr><tr><th>Frontend</th><td>${tuner.frontend_accessible===false?'Unavailable':'Available'}</td></tr><tr><th>Signal</th><td>${Number.isFinite(Number(tuner.signal_percent))?`${esc(tuner.signal_percent)}%`:'Unknown'}</td></tr><tr><th>Quality</th><td>${Number.isFinite(Number(tuner.quality_percent))?`${esc(tuner.quality_percent)}%`:'Unknown'}</td></tr><tr><th>Delivery</th><td>${esc(tuner.delivery_systems||'Unknown')}</td></tr></tbody></table>`;}
  function selectedProgramCard(){const channel=channels.find(c=>channelId(c)===selectedId);if(!channel)return '';const current=nowProgram(selectedId),next=nextProgram(selectedId),progress=current?programProgress(current):0;return `<div class="live-tv-now-card"><div>${channelIdentity(channel)}</div><div><strong>NOW</strong><span>${current?esc(programTitle(current)):'No current guide data'}</span><small>${current?esc(timeRange(current)):''}</small>${current?`<div class="live-tv-progress"><i style="width:${progress.toFixed(1)}%"></i></div>`:''}</div><div><strong>NEXT</strong><span>${next?esc(programTitle(next)):'No upcoming guide data'}</span><small>${next?esc(timeRange(next)):''}</small></div></div>`;}
  function renderBody(message=''){const body=document.getElementById('liveTvFullBody');if(!body)return;body.innerHTML=`<h2 class="module-heading">LIVE TV GUIDE</h2>${tunerTable()}${selectedProgramCard()}<div class="status-line" id="liveTvFullStatus">${esc(message||`${channels.length} CHANNEL${channels.length===1?'':'S'} • ${programs.length} GUIDE EVENT${programs.length===1?'':'S'}`)}</div><div class="module-result-list live-tv-guide" id="liveTvGuideRows">${guideRows()}</div>`;body.querySelectorAll('[data-live-channel-logo]').forEach(image=>image.addEventListener('error',()=>image.remove(),{once:true}));body.querySelectorAll('[data-live-guide-id]').forEach(row=>row.addEventListener('click',()=>selectChannel(row.dataset.liveGuideId)));}
  function scrollSelected(behavior='smooth'){requestAnimationFrame(()=>{const row=[...document.querySelectorAll('[data-live-guide-id]')].find(x=>x.dataset.liveGuideId===selectedId);row?.scrollIntoView({block:'nearest',behavior});row?.focus({preventScroll:true});});}
  function selectChannel(id,message=''){const channel=channels.find(c=>channelId(c)===String(id||''));if(!channel)return;selectedId=channelId(channel);remember();const program=nowProgram(selectedId);renderBody(message||`Selected ${channelName(channel)}${program?` • ${programTitle(program)}`:''}`);scrollSelected();}
  function moveSelection(delta){const selectable=channels.filter(c=>channelId(c));if(!selectable.length)return;let index=selectable.findIndex(c=>channelId(c)===selectedId);if(index<0)index=delta<0?selectable.length:-1;index=(index+delta+selectable.length)%selectable.length;selectChannel(channelId(selectable[index]));}
  function focusNow(){const current=channels.find(c=>nowProgram(channelId(c)));if(!current){renderBody('No current guide event is available to focus.');return;}const id=channelId(current),program=nowProgram(id);selectChannel(id,`NOW • ${channelName(current)}${program?` • ${programTitle(program)}`:''}`);}
  async function watchSelected(){if(!selectedId){renderBody('Select a channel first.');return;}const data=await run('watch',{id:selectedId});const channel=channels.find(c=>channelId(c)===selectedId)||{},program=nowProgram(selectedId);if(data&&(data.url||data.streamUrl)&&hostRef?.playUrl)hostRef.playUrl(data.url||data.streamUrl,program?`${channelName(channel)} • ${programTitle(program)}`:channelName(channel));}
  function liveTvKeydown(event){const target=event.target;if(target&&(['INPUT','TEXTAREA','SELECT'].includes(target.tagName)||target.isContentEditable))return;if(event.key==='ArrowDown'){event.preventDefault();moveSelection(1);return;}if(event.key==='ArrowUp'){event.preventDefault();moveSelection(-1);return;}if(event.key==='Home'&&channels.length){event.preventDefault();selectChannel(channelId(channels[0]));return;}if(event.key==='End'&&channels.length){event.preventDefault();selectChannel(channelId(channels[channels.length-1]));return;}if(event.key==='Enter'&&selectedId){event.preventDefault();watchSelected();}}
  function bindKeyboard(){if(keyboardBound)return;document.addEventListener('keydown',liveTvKeydown);keyboardBound=true;}
  function unbindKeyboard(){if(!keyboardBound)return;document.removeEventListener('keydown',liveTvKeydown);keyboardBound=false;}
  function absorb(data){if(Array.isArray(data.channels))channels=data.channels;if(Array.isArray(data.programs))programs=data.programs;if(data.tuner)tuner=data.tuner;else if(Array.isArray(data.tuners)&&data.tuners[0])tuner=data.tuners[0];if(selectedId&&!channels.some(c=>channelId(c)===selectedId))selectedId='';remember();}
  async function run(action,extra={}){const status=document.getElementById('liveTvFullStatus');if(status)status.textContent=`LIVE TV • ${action.toUpperCase()}...`;try{const data=await call(action,extra);absorb(data);renderBody(data.status||`${action} complete.`);return data;}catch(err){renderBody(`Live TV host bridge unavailable: ${err.message||err}`);return null;}}
  async function renderLiveTv(host){hostRef=host;restore();bindKeyboard();shell(`<div class="module-toolbar">${button('Guide','liveGuide',true)}${button('Now','liveNow')}${button('Scan Channels','liveScan')}${button('Watch Live','liveWatch')}${button('Stop Live','liveStop')}${button('Refresh Guide','liveRefreshGuide')}${button('Record','liveRecord')}</div><div id="liveTvFullBody"></div>`);bind('liveGuide',()=>run('guide'));bind('liveNow',focusNow);bind('liveScan',()=>run('scan'));bind('liveRefreshGuide',()=>run('refresh-guide'));bind('liveStop',()=>run('stop'));bind('liveRecord',()=>selectedId?run('record',{id:selectedId}):renderBody('Select a channel before recording.'));bind('liveWatch',watchSelected);renderBody();if(selectedId)scrollSelected('auto');const data=await run('guide');if(!data&&channels.length)renderBody('Showing last saved Live TV guide because the host bridge is currently unavailable.');}
  window.NougatWebModules.activate=function(name,host){if(name==='livetv')return renderLiveTv(host);unbindKeyboard();return previous(name,host);};
})();