(() => {
  'use strict';
  if(!window.NougatWebModules)return;
  const previous=window.NougatWebModules.activate.bind(window.NougatWebModules);
  const root=()=>document.getElementById('moduleView');
  const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const button=(label,id,active=false,extra='')=>`<button type="button" class="sheet-button${active?' active-tool':''}" id="${id}" ${extra}>${esc(label)}</button>`;
  const bind=(id,fn)=>{const el=document.getElementById(id);if(el)el.addEventListener('click',fn);};
  const shell=(html)=>{const r=root();if(!r)return null;r.innerHTML=`<div class="module-workspace">${html}</div>`;return r.querySelector('.module-workspace');};
  const services=['Local','Internet','AM','FM','HD Radio','DAB / DAB+','DRM','Longwave','Mediumwave','Shortwave','Weather','Emergency','Public Safety','Police','Fire','EMS','Government','Military','Airband','Marine','Railroad','CB','FRS / GMRS','MURS','Amateur / Ham','Business','Utilities','Trunked','P25','DMR','NXDN','TETRA','Paging','ISS / Sat','Weather Sat','Amateur Sat','Favorites','Recordings','Cellular Lab'];
  const modulations=['AM','NFM','WFM','USB','LSB','CW','DAB/DAB+','DRM','P25','RAW IQ'];
  const steps=[2500,5000,6250,10000,12500,25000,50000,100000,200000,1000000];
  let service='Internet';
  let hostRef=null;

  function readState(){try{return {...{frequencyHz:100100000,modulation:'WFM',stepHz:100000,gain:50,squelch:0,device:0},...(JSON.parse(localStorage.getItem('nougat-web-radio-state')||'{}')||{})};}catch(_){return {frequencyHz:100100000,modulation:'WFM',stepHz:100000,gain:50,squelch:0,device:0};}}
  function saveState(s){localStorage.setItem('nougat-web-radio-state',JSON.stringify(s));}
  function favorites(){try{return JSON.parse(localStorage.getItem('nougat-web-radio-presets')||'[]')||[];}catch(_){return [];}}
  function saveFavorites(f){localStorage.setItem('nougat-web-radio-presets',JSON.stringify(f.slice(0,100)));}
  function mhz(hz){return (Number(hz)/1000000).toFixed(Number(hz)%1000000?4:3);}
  function servicePreset(name,state){
    const map={FM:[100100000,'WFM',100000],AM:[1000000,'AM',10000],Weather:[162550000,'NFM',25000],Airband:[121500000,'AM',25000],Marine:[156800000,'NFM',25000],'Amateur / Ham':[146520000,'NFM',5000],'ISS / Sat':[145800000,'NFM',5000],CB:[27185000,'AM',10000],'FRS / GMRS':[462562500,'NFM',12500],MURS:[151820000,'NFM',12500],Shortwave:[10000000,'AM',5000],Longwave:[200000,'AM',1000],Mediumwave:[1000000,'AM',10000],P25:[851000000,'P25',12500],'DAB / DAB+':[220352000,'DAB/DAB+',1712000],DRM:[10000000,'DRM',5000]};
    const p=map[name];if(p){state.frequencyHz=p[0];state.modulation=p[1];state.stepHz=p[2];}
    return state;
  }
  async function action(name,extra={}){
    const s=readState();const params=new URLSearchParams({action:name,service,frequency:String(s.frequencyHz),modulation:s.modulation,step:String(s.stepHz),gain:String(s.gain),squelch:String(s.squelch),...extra});
    const base=hostRef?.baseUrl?hostRef.baseUrl():'';const response=await fetch(`${base}/nougat/v1/radio?${params}`,{cache:'no-store'});let data={};try{data=await response.json();}catch(_){data={};}if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data;
  }
  function setStatus(text){const el=document.getElementById('radioFullStatus');if(el)el.textContent=text;}
  function updateLabels(){const s=readState();const freq=document.getElementById('radioFreq');if(freq)freq.value=mhz(s.frequencyHz);const gain=document.getElementById('radioGain');if(gain){gain.value=s.gain;document.getElementById('radioGainValue').textContent=`${s.gain}%`;}const squelch=document.getElementById('radioSquelch');if(squelch){squelch.value=s.squelch;document.getElementById('radioSquelchValue').textContent=String(s.squelch);}}

  function renderFavorites(){const list=favorites();return `<div class="module-result-list">${list.length?list.map((f,i)=>`<button type="button" class="module-result-row" data-radio-favorite="${i}"><span>${esc(f.name)}</span><span>${mhz(f.frequencyHz)} MHz</span><span>${esc(f.modulation)}</span></button>`).join(''):'<div class="module-empty">No saved radio favorites.</div>'}</div>`;}
  function renderRecordings(){return `<div class="module-output">Recordings made by the standalone host remain on the host. The web bridge will list them here when the Radio endpoint exposes recordings.</div><div class="module-toolbar">${button('Refresh Recordings','radioRefreshRecordings')}</div><div class="module-result-list" id="radioRecordingList"></div>`;}
  function renderRadio(host){
    hostRef=host;let s=servicePreset(service,readState());saveState(s);
    const special=service==='Favorites'||service==='Recordings';
    shell(`<div class="module-toolbar" id="radioFullServices">${services.map((x,i)=>button(x,`radioFullService${i}`,x===service)).join('')}</div><h2 class="module-heading">RADIO • ${esc(service.toUpperCase())}</h2>${service==='Favorites'?renderFavorites():service==='Recordings'?renderRecordings():`<div class="module-panel-grid"><div class="module-field"><span>FREQUENCY MHz</span><input id="radioFreq" type="number" min="0.001" max="6000" step="0.000001" value="${mhz(s.frequencyHz)}"></div><div class="module-field"><span>MODULATION</span><select id="radioMod">${modulations.map(m=>`<option ${m===s.modulation?'selected':''}>${esc(m)}</option>`).join('')}</select></div><div class="module-field"><span>TUNING STEP</span><select id="radioStep">${steps.map(v=>`<option value="${v}" ${Number(s.stepHz)===v?'selected':''}>${v>=1000000?(v/1000000)+' MHz':(v/1000)+' kHz'}</option>`).join('')}</select></div></div><div class="module-toolbar">${button('◀ STEP','radioStepDown')}${button('STEP ▶','radioStepUp')}${button('Receive','radioReceive')}${button('Stop','radioStopFull')}${button('Scan','radioScanFull')}${button('Record','radioRecord')}${button('Favorite','radioFavoriteFull')}${button('Refresh Hardware','radioRefreshHardware')}${button('TX Chain Self Test','radioTxTest')}</div><div class="module-panel-grid"><div class="module-field"><span>GAIN <b id="radioGainValue">${s.gain}%</b></span><input id="radioGain" type="range" min="0" max="100" value="${s.gain}"></div><div class="module-field"><span>SQUELCH <b id="radioSquelchValue">${s.squelch}</b></span><input id="radioSquelch" type="range" min="-100" max="100" value="${s.squelch}"></div></div><div class="module-output" id="radioFullStatus">${service==='Internet'?'Internet Radio ready.':'Receiver profile ready. Hardware state is reported only when the Nougat host bridge returns it.'}</div>`}`);
    services.forEach((x,i)=>bind(`radioFullService${i}`,()=>{service=x;renderRadio(hostRef);}));
    if(service==='Favorites'){root().querySelectorAll('[data-radio-favorite]').forEach(row=>row.addEventListener('click',()=>{const f=favorites()[Number(row.dataset.radioFavorite)];if(!f)return;const next=readState();next.frequencyHz=f.frequencyHz;next.modulation=f.modulation;saveState(next);service=f.service||'Local';renderRadio(hostRef);}));return;}
    if(service==='Recordings'){bind('radioRefreshRecordings',async()=>{const list=document.getElementById('radioRecordingList');list.innerHTML='<div class="module-empty">Loading...</div>';try{const data=await action('recordings');const rows=Array.isArray(data.recordings)?data.recordings:[];list.innerHTML=rows.length?rows.map(x=>`<div class="module-result-row"><span>${esc(x.name||x)}</span><span>${esc(x.duration||'')}</span><span>${esc(x.size||'')}</span></div>`).join(''):'<div class="module-empty">No host recordings returned.</div>';}catch(err){list.innerHTML=`<div class="module-empty">Radio host bridge unavailable: ${esc(err.message||err)}</div>`;}});return;}
    const saveControls=()=>{const x=readState();x.frequencyHz=Math.max(1000,Math.min(6000000000,Number(document.getElementById('radioFreq').value)*1000000||x.frequencyHz));x.modulation=document.getElementById('radioMod').value;x.stepHz=Number(document.getElementById('radioStep').value)||x.stepHz;x.gain=Number(document.getElementById('radioGain').value);x.squelch=Number(document.getElementById('radioSquelch').value);saveState(x);return x;};
    document.getElementById('radioFreq').addEventListener('change',saveControls);document.getElementById('radioMod').addEventListener('change',saveControls);document.getElementById('radioStep').addEventListener('change',saveControls);document.getElementById('radioGain').addEventListener('input',()=>{saveControls();updateLabels();});document.getElementById('radioSquelch').addEventListener('input',()=>{saveControls();updateLabels();});
    bind('radioStepDown',()=>{const x=saveControls();x.frequencyHz=Math.max(1000,x.frequencyHz-x.stepHz);saveState(x);updateLabels();});bind('radioStepUp',()=>{const x=saveControls();x.frequencyHz=Math.min(6000000000,x.frequencyHz+x.stepHz);saveState(x);updateLabels();});
    bind('radioReceive',async()=>{saveControls();if(service==='Internet'){hostRef?.playUrl&&hostRef.playUrl('https://ice1.somafm.com/groovesalad-128-mp3','SomaFM Groove Salad');return;}setStatus('Starting receiver through Nougat host...');try{const data=await action('receive');setStatus(data.status||'Receiver started.');}catch(err){setStatus(`Radio host bridge unavailable: ${err.message||err}`);}});
    bind('radioStopFull',async()=>{const p=document.getElementById('player');if(p){p.pause();if(p.src)p.removeAttribute('src');p.load();}try{const data=await action('stop');setStatus(data.status||'Radio stopped.');}catch(_){setStatus('Browser playback stopped. Host RF stop was not available through the current bridge.');}});
    bind('radioScanFull',async()=>{saveControls();setStatus(`Scanning ${service} through Nougat host...`);try{const data=await action('scan');setStatus(data.status||JSON.stringify(data,null,2));}catch(err){setStatus(`Radio host bridge unavailable: ${err.message||err}`);}});
    bind('radioRecord',async()=>{saveControls();try{const data=await action('record');setStatus(data.status||'Recording state changed.');}catch(err){setStatus(`Record requires the Nougat host Radio bridge: ${err.message||err}`);}});
    bind('radioFavoriteFull',()=>{const x=saveControls();const f=favorites();const name=`${service} ${mhz(x.frequencyHz)} MHz`;if(!f.some(v=>v.frequencyHz===x.frequencyHz&&v.modulation===x.modulation))f.push({name,service,frequencyHz:x.frequencyHz,modulation:x.modulation});saveFavorites(f);setStatus(`Saved ${name}.`);});
    bind('radioRefreshHardware',async()=>{try{const data=await action('status');setStatus(data.status||JSON.stringify(data,null,2));}catch(err){setStatus(`Hardware status unavailable: ${err.message||err}`);}});
    bind('radioTxTest',async()=>{setStatus('Running generated-IQ TX chain self-test only. No RF transmit request is made by this control.');try{const data=await action('tx-self-test');setStatus(data.status||JSON.stringify(data,null,2));}catch(err){setStatus(`TX chain self-test bridge unavailable: ${err.message||err}`);}});
  }
  window.NougatWebModules.activate=function(name,host){if(name==='radio')return renderRadio(host);return previous(name,host);};
})();