#!/bin/sh
cat <<'EOF'
[{"GuideNumber":"10.1","GuideName":"KAKE","URL":"http://192.168.1.165:5004/auto/v10.1"},{"GuideNumber":"3.1","GuideName":"KSNW-DT","URL":"http://192.168.1.165:5004/auto/v3.1"}]
EOF
